# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\maki-e\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vx_integration\Second_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VXDialogBase(object):
    def setupUi(self, VXDialogBase):
        VXDialogBase.setObjectName("VXDialogBase")
        VXDialogBase.resize(887, 528)
        VXDialogBase.setStyleSheet("background: rgba(255, 255, 255,1)")
        self.button_box = QtWidgets.QDialogButtonBox(VXDialogBase)
        self.button_box.setGeometry(QtCore.QRect(680, 461, 161, 41))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.Dodaj = QtWidgets.QPushButton(VXDialogBase)
        self.Dodaj.setGeometry(QtCore.QRect(310, 160, 81, 23))
        self.Dodaj.setObjectName("Dodaj")
        self.Logo = QtWidgets.QLabel(VXDialogBase)
        self.Logo.setGeometry(QtCore.QRect(310, 230, 71, 71))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/plugins/VX_integration/icon.png"))
        self.Logo.setObjectName("Logo")
        self.frame = QtWidgets.QFrame(VXDialogBase)
        self.frame.setGeometry(QtCore.QRect(410, 79, 461, 371))
        self.frame.setStyleSheet("background: rgba(255, 255, 255,1)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(30, 70, 201, 271))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.listWidget_2 = QtWidgets.QListWidget(self.frame)
        self.listWidget_2.setGeometry(QtCore.QRect(240, 70, 191, 271))
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.Pola_WinCan = QtWidgets.QLabel(self.frame)
        self.Pola_WinCan.setGeometry(QtCore.QRect(30, 40, 91, 21))
        self.Pola_WinCan.setStyleSheet("background: rgba(255, 255, 255,0)")
        self.Pola_WinCan.setObjectName("Pola_WinCan")
        self.Dostepne_pola = QtWidgets.QLabel(self.frame)
        self.Dostepne_pola.setGeometry(QtCore.QRect(10, 0, 91, 31))
        self.Dostepne_pola.setStyleSheet("background: rgba(255, 255, 255,0)")
        self.Dostepne_pola.setObjectName("Dostepne_pola")
        self.Pola_warstwy = QtWidgets.QLabel(self.frame)
        self.Pola_warstwy.setGeometry(QtCore.QRect(240, 40, 81, 21))
        self.Pola_warstwy.setStyleSheet("background: rgba(255, 255, 255,0)")
        self.Pola_warstwy.setObjectName("Pola_warstwy")
        self.frame_2 = QtWidgets.QFrame(VXDialogBase)
        self.frame_2.setGeometry(QtCore.QRect(0, 70, 291, 381))
        self.frame_2.setStyleSheet("background: rgba(255, 255, 255,1)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 80, 251, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.Dostepne_pola_2 = QtWidgets.QLabel(self.frame_2)
        self.Dostepne_pola_2.setGeometry(QtCore.QRect(10, 0, 91, 31))
        self.Dostepne_pola_2.setStyleSheet("background: rgba(255, 255, 255,0)")
        self.Dostepne_pola_2.setObjectName("Dostepne_pola_2")
        self.Dodaj_2 = QtWidgets.QPushButton(VXDialogBase)
        self.Dodaj_2.setGeometry(QtCore.QRect(310, 190, 81, 23))
        self.Dodaj_2.setObjectName("Dodaj_2")
        self.frame.raise_()
        self.button_box.raise_()
        self.Dodaj.raise_()
        self.Logo.raise_()
        self.frame_2.raise_()
        self.Dodaj_2.raise_()

        self.retranslateUi(VXDialogBase)
        self.button_box.accepted.connect(VXDialogBase.accept)
        self.button_box.rejected.connect(VXDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(VXDialogBase)

    def retranslateUi(self, VXDialogBase):
        _translate = QtCore.QCoreApplication.translate
        VXDialogBase.setWindowTitle(_translate("VXDialogBase", "WinCan Plugin"))
        self.Dodaj.setText(_translate("VXDialogBase", "< Dodaj"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(1)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(2)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(3)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(4)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(5)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(6)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(7)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(8)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(9)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget.item(10)
        item.setText(_translate("VXDialogBase", "2"))
        item = self.listWidget.item(11)
        item.setText(_translate("VXDialogBase", "3"))
        item = self.listWidget.item(12)
        item.setText(_translate("VXDialogBase", "4"))
        item = self.listWidget.item(13)
        item.setText(_translate("VXDialogBase", "5"))
        item = self.listWidget.item(14)
        item.setText(_translate("VXDialogBase", "6"))
        item = self.listWidget.item(15)
        item.setText(_translate("VXDialogBase", "7"))
        item = self.listWidget.item(16)
        item.setText(_translate("VXDialogBase", "8"))
        item = self.listWidget.item(17)
        item.setText(_translate("VXDialogBase", "9"))
        item = self.listWidget.item(18)
        item.setText(_translate("VXDialogBase", "0"))
        item = self.listWidget.item(19)
        item.setText(_translate("VXDialogBase", "-"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(5)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(6)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(7)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(8)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(9)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(10)
        item.setText(_translate("VXDialogBase", "1"))
        item = self.listWidget_2.item(11)
        item.setText(_translate("VXDialogBase", "2"))
        item = self.listWidget_2.item(12)
        item.setText(_translate("VXDialogBase", "3"))
        item = self.listWidget_2.item(13)
        item.setText(_translate("VXDialogBase", "4"))
        item = self.listWidget_2.item(14)
        item.setText(_translate("VXDialogBase", "5"))
        item = self.listWidget_2.item(15)
        item.setText(_translate("VXDialogBase", "6"))
        item = self.listWidget_2.item(16)
        item.setText(_translate("VXDialogBase", "7"))
        item = self.listWidget_2.item(17)
        item.setText(_translate("VXDialogBase", "8"))
        item = self.listWidget_2.item(18)
        item.setText(_translate("VXDialogBase", "9"))
        item = self.listWidget_2.item(19)
        item.setText(_translate("VXDialogBase", "0"))
        item = self.listWidget_2.item(20)
        item.setText(_translate("VXDialogBase", "-"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.Pola_WinCan.setText(_translate("VXDialogBase", "Pola WinCan"))
        self.Dostepne_pola.setText(_translate("VXDialogBase", "Dostępne pola"))
        self.Pola_warstwy.setText(_translate("VXDialogBase", "Pola warstwy"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("VXDialogBase", "WinCan"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("VXDialogBase", "Map"))
        self.Dostepne_pola_2.setText(_translate("VXDialogBase", "Mapowanie pola"))
        self.Dodaj_2.setText(_translate("VXDialogBase", "Usuń >"))


import resources_rc
